---
# Setup a Docker registry

- name: docker registry | create storage directory
  become: yes
  file:
    path: "{{ docker_registry_storage_directory }}"
    state: directory
  when: 'docker_registry_storage_directory | length > 0'

# Needed for Ansible docker_image module
- name: docker registry | docker-python
  become: yes
  yum:
    name: docker-python
    state: present

- name: docker registry | pull registry image
  become: yes
  docker_image:
    name: registry:{{ docker_registry_version }}

- name: docker registry | systemd service file
  become: yes
  template:
    src: systemd-system-docker-registry-service.j2
    dest: /etc/systemd/system/docker-registry.service
  notify:
    - restart docker-registry

- name: docker registry | enable
  become: yes
  systemd:
    daemon_reload: yes
    name: docker-registry
    state: started
    enabled: yes
